title: Qiwen Ma
email: stellama853@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Shut Down The Heart, And Open Your Eyes.
permalink: ':title/'
baseurl: "" 
url: "" 

# Author settings
author: Gabriel Chen 
author-pic:
about-author: 

# Contact links
email: stellama853@gmail.com # Add your Email address
phone: +86 15666130989
website: stellam1001.github.io/ # Add your website, do not add http://
linkedin: www.linkedin.com/in/qiwen-ma-776644310# Add your Linkedin handle
github: https://github.com/StellaM1001/# Add your Github handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle
mastodon: gabriel

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Paginate
paginate: 6
paginate_path: /page:num/

# collections
collections:
  - books
  - booktags
  - movies
  - movietags
  - images

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-feed

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
